chaihens:
  voucher:
    web:
      #HTTP 监听端口
      port: 8085
      #嵌入式Web服务器的线程池配置
      threadPool:
        maxThreads: 200
        minThreads: 8
        idleTimeout: 60000
    dataSource:
      #数据库配置项参照 com.zaxxer.hikari.HikariConfig
      driverClassName: com.mysql.jdbc.Driver
      jdbcUrl: jdbc:mysql://192.168.99.100:32768/chaihens?zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=utf8
      username: root
      password: 123456
    redis:
      host: 192.168.99.100
      port: 32768
      maxTotal: 300
      maxIdle: 20
      maxWaitMillis: 10000
      testOnBorrow: true
      testOnReturn: true